language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo generate
after_script:
  - cd ./public
  - git init
  - git config user.name "OpenCAS"
  - git config user.email "admin@opencas.org"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - source

env:
 global:
   - GH_REF: github.com/opencas/opencas.github.io